#!/bin/bash
# Validates Caddy configs generated by the shared renderer.
# Covers both CI_E2E mode and standard install mode.
# Run from project root. Requires: caddy (or docker)
# Usage: ./test/validate_caddy_config.sh

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT" || exit 1

# shellcheck source=../exports.sh
source "$PROJECT_ROOT/exports.sh"
# shellcheck source=../lib/common_functions.sh
source "$PROJECT_ROOT/lib/common_functions.sh"
# shellcheck source=../install/web/caddy_helpers.sh
source "$PROJECT_ROOT/install/web/caddy_helpers.sh"

generated_files=()

cleanup() {
    if [[ ${#generated_files[@]} -gt 0 ]]; then
        rm -f "${generated_files[@]}"
    fi
}
trap cleanup EXIT

validate_with_caddy() {
    local caddyfile="$1"
    local caddy_cmd=(caddy)
    if command -v sudo &>/dev/null && sudo -n true 2>/dev/null; then
        caddy_cmd=(sudo caddy)
    fi

    echo "Formatting with caddy fmt..."
    # Format as current user; sudo+caddy can fail to overwrite /tmp files.
    caddy fmt --overwrite "$caddyfile" >/dev/null 2>&1 || true

    echo "Checking adapter translation with caddy adapt..."
    if ! "${caddy_cmd[@]}" adapt --config "$caddyfile" --adapter caddyfile >/dev/null; then
        echo "caddy adapt failed for $caddyfile"
        return 1
    fi

    echo "Validating with caddy validate..."
    if ! "${caddy_cmd[@]}" validate --config "$caddyfile" --adapter caddyfile; then
        echo "caddy validate failed for $caddyfile"
        return 1
    fi

    return 0
}

validate_with_docker() {
    local caddyfile="$1"
    echo "Validating with docker run caddy..."
    docker run --rm -v "$caddyfile:/etc/caddy/Caddyfile" caddy:2 \
        sh -c "caddy fmt --overwrite /etc/caddy/Caddyfile >/dev/null && caddy adapt --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null && caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile"
}

validate_generated_config() {
    local mode="$1"
    local ci_mode="$2"
    local caddyfile="/tmp/caddy_validate_${mode}_$$.Caddyfile"
    generated_files+=("$caddyfile")

    if [[ "$ci_mode" == "true" ]]; then
        export CI_E2E=true
    else
        unset CI_E2E
    fi

    create_caddy_config_auto_https "${SERVER_NAME:-rpc.sharedtools.org}" "$caddyfile"

    if command -v caddy &>/dev/null && validate_with_caddy "$caddyfile"; then
        echo "✓ Caddy config is valid ($mode)"
        return 0
    fi

    if command -v docker &>/dev/null && validate_with_docker "$caddyfile"; then
        echo "✓ Caddy config is valid ($mode)"
        return 0
    fi

    echo "✗ Caddy config validation failed ($mode)"
    if ! command -v caddy &>/dev/null && ! command -v docker &>/dev/null; then
        echo "Error: caddy or docker required for validation"
    fi
    echo "Generated config at: $caddyfile"
    return 1
}

validate_generated_config "ci_e2e" "true"
validate_generated_config "standard" "false"

echo "✓ All generated Caddy configs are valid"
