#!/bin/bash
# Validates the Nginx config generated by the shared edge policy renderer.
# Run from project root. Requires either:
#   1) nginx binary available locally (root/sudo optional), or
#   2) docker (fallback syntax check in nginx container)
# Usage: ./test/validate_nginx_config.sh

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT" || exit 1

# shellcheck source=../exports.sh
source "$PROJECT_ROOT/exports.sh"
# shellcheck source=../lib/common_functions.sh
source "$PROJECT_ROOT/lib/common_functions.sh"
# shellcheck source=../install/web/nginx_helpers.sh
source "$PROJECT_ROOT/install/web/nginx_helpers.sh"

export CI_E2E=true

VALIDATE_ROOT="$(mktemp -d /tmp/nginx_validate_XXXXXX)"
NGINX_ETC="$VALIDATE_ROOT/etc/nginx"
NGINX_CONF="$NGINX_ETC/nginx.conf"
NGINX_POLICY="$NGINX_ETC/conf.d/eth2-edge-policy.conf"
NGINX_SITE="$NGINX_ETC/sites-enabled/default"

mkdir -p "$NGINX_ETC/conf.d" "$NGINX_ETC/sites-enabled"

create_nginx_config "${SERVER_NAME:-rpc.sharedtools.org}" "$NGINX_SITE"
render_nginx_http_policy_file "$NGINX_POLICY"

has_passwordless_sudo() {
    command -v sudo &>/dev/null && sudo -n true 2>/dev/null
}

cleanup_validate_root() {
    if [[ ! -d "$VALIDATE_ROOT" ]]; then
        return 0
    fi

    if [[ "$(id -u)" -eq 0 ]]; then
        rm -rf "$VALIDATE_ROOT"
        return 0
    fi

    if has_passwordless_sudo; then
        sudo rm -rf "$VALIDATE_ROOT"
        return 0
    fi

    chmod -R u+w "$VALIDATE_ROOT" 2>/dev/null || true
    rm -rf "$VALIDATE_ROOT" 2>/dev/null || true
}

trap cleanup_validate_root EXIT

if [[ "$(id -u)" -ne 0 ]] && ! has_passwordless_sudo; then
    local_cache_root="$VALIDATE_ROOT/var/cache/nginx"
    local_log_root="$VALIDATE_ROOT/var/log/nginx"
    mkdir -p "$local_cache_root/rpc_cache" "$local_cache_root/client_temp"
    mkdir -p "$local_log_root"
    touch "$local_log_root/access.log" "$local_log_root/error.log"
    sed -i \
        -e "s|/var/cache/nginx/rpc_cache|$local_cache_root/rpc_cache|g" \
        -e "s|/var/cache/nginx/client_temp|$local_cache_root/client_temp|g" \
        "$NGINX_POLICY"
    sed -i \
        -e "s|/var/log/nginx/access.log|$local_log_root/access.log|g" \
        -e "s|/var/log/nginx/error.log|$local_log_root/error.log|g" \
        "$NGINX_SITE"
    sed -i \
        -e 's/listen 80;/listen 18080;/g' \
        -e 's/listen \[::\]:80;/listen [::]:18080;/g' \
        "$NGINX_SITE"
fi

cat > "$NGINX_CONF" << EOF
worker_processes 1;
error_log ${VALIDATE_ROOT}/error.log warn;
pid ${VALIDATE_ROOT}/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log ${VALIDATE_ROOT}/access.log;
    include ${NGINX_ETC}/conf.d/*.conf;
    include ${NGINX_ETC}/sites-enabled/*;
}
EOF

can_validate_with_local_nginx() {
    command -v nginx &>/dev/null
}

validate_with_local_nginx() {
    echo "Validating with local nginx -t..."
    if [[ "$(id -u)" -eq 0 ]]; then
        mkdir -p /var/cache/nginx/rpc_cache /var/cache/nginx/client_temp
        nginx -t -c "$NGINX_CONF"
    elif has_passwordless_sudo; then
        sudo mkdir -p /var/cache/nginx/rpc_cache /var/cache/nginx/client_temp
        sudo nginx -t -c "$NGINX_CONF"
    else
        nginx -t -c "$NGINX_CONF"
    fi
}

validate_with_docker() {
    echo "Validating with docker run nginx..."
    docker run --rm \
        -v "$VALIDATE_ROOT:$VALIDATE_ROOT" \
        -v "$VALIDATE_ROOT/var/cache/nginx:/var/cache/nginx" \
        nginx:1.27-alpine \
        sh -c "mkdir -p /var/cache/nginx/rpc_cache /var/cache/nginx/client_temp && nginx -t -c $NGINX_CONF"
}

if can_validate_with_local_nginx && validate_with_local_nginx; then
    echo "✓ Nginx config is valid"
    exit 0
fi

if command -v docker &>/dev/null && validate_with_docker; then
    echo "✓ Nginx config is valid"
    exit 0
fi

echo "✗ Nginx config validation failed"
if ! command -v nginx &>/dev/null && ! command -v docker &>/dev/null; then
    echo "Error: nginx or docker is required for validation"
fi
exit 1
