#!/bin/bash

# Eth2 Quick Start - Help & Tool Discovery
# Shows all available scripts and the two-phase installation model
# Usage: ./help.sh [--help|-h]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

# Source colors (minimal - help.sh should work even if common_functions has issues)
if [[ -f "$SCRIPT_DIR/lib/common_functions.sh" ]]; then
    # shellcheck source=lib/common_functions.sh
    source "$SCRIPT_DIR/lib/common_functions.sh"
else
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    BOLD='\033[1m'
    NC='\033[0m'
fi

show_help_usage() {
    echo ""
    echo "Usage: ./help.sh [--help|-h]"
    echo ""
    echo "  --help, -h    Show this usage (you're here!)"
    echo ""
    echo "Run without args to see the full tool reference."
    echo ""
    exit 0
}

for arg in "$@"; do
    case "$arg" in
        --help|-h)
            show_help_usage
            ;;
    esac
done

# =============================================================================
# OUTPUT
# =============================================================================

echo ""
echo -e "${BOLD}${GREEN}====================================================${NC}"
echo -e "${BOLD}${GREEN}  Eth2 Quick Start - Tools & Scripts Reference${NC}"
echo -e "${BOLD}${GREEN}====================================================${NC}"
echo ""

# -----------------------------------------------------------------------------
# TWO-PHASE INSTALLATION (prominent - explains the model)
# -----------------------------------------------------------------------------
echo -e "${BOLD}${YELLOW}▼ TWO-PHASE INSTALLATION${NC}"
echo -e "${YELLOW}This project uses a secure two-phase model. You MUST reboot between phases.${NC}"
echo ""
echo "  Phase 1 (as root):"
echo "    • System hardening (SSH, firewall, fail2ban, AIDE)"
echo "    • Creates secure non-root user"
echo "    • Copies repo to user's home"
echo -e "    • ${RED}Ends with mandatory reboot${NC}"
echo ""
echo "  Phase 2 (as new user, after reboot):"
echo "    • Installs execution + consensus clients"
echo "    • Optional MEV (MEV-Boost or Commit-Boost)"
echo "    • Health check"
echo ""
echo "  Two ways to run:"
echo "    A) One-liner:  curl ... | sudo bash  →  install_phase1.sh  →  reboot  →  install_phase2.sh"
echo "    B) Direct:     git clone  →  run_1.sh  →  reboot  →  run_2.sh"
echo ""

# -----------------------------------------------------------------------------
# CORE INSTALLATION SCRIPTS
# -----------------------------------------------------------------------------
echo -e "${BOLD}${BLUE}▼ CORE INSTALLATION${NC}"
echo ""
printf "  %-30s %s\n" "run_1.sh" "Phase 1: System hardening (run as root, then reboot)"
printf "  %-30s %s\n" "run_2.sh" "Phase 2: Client installation (run as new user)"
printf "  %-30s %s\n" "install_phase1.sh" "Phase 1 (generated by configure.sh)"
printf "  %-30s %s\n" "install_phase2.sh" "Phase 2 (generated by configure.sh)"
printf "  %-30s %s\n" "install.sh" "Bootstrap: clone repo + launch configure wizard"
printf "  %-30s %s\n" "install/utils/configure.sh" "TUI wizard: generates phase scripts + user config"
echo ""

# -----------------------------------------------------------------------------
# MAINTENANCE
# -----------------------------------------------------------------------------
echo -e "${BOLD}${BLUE}▼ MAINTENANCE${NC}"
echo ""
printf "  %-30s %s\n" "install/utils/update.sh" "Update Ethereum clients (geth, prysm, MEV-Boost)"
printf "  %-30s %s\n" "install/utils/update_all.sh" "Update both repo + software (--git-only, --software-only)"
printf "  %-30s %s\n" "install/utils/update_git.sh" "Update eth2-quickstart from git"
printf "  %-30s %s\n" "install/utils/refresh.sh" "Restart all Ethereum services"
echo ""

# -----------------------------------------------------------------------------
# DIAGNOSTICS
# -----------------------------------------------------------------------------
echo -e "${BOLD}${BLUE}▼ DIAGNOSTICS${NC}"
echo ""
printf "  %-30s %s\n" "install/utils/doctor.sh" "Health check: system, services, config, ports"
printf "  %-30s %s\n" "install/utils/stats.sh" "Client versions, service status, error scan"
printf "  %-30s %s\n" "install/utils/view_logs.sh" "View run_1, run_2, security logs (--run1, --run2, -f)"
echo ""

# -----------------------------------------------------------------------------
# CONFIGURATION
# -----------------------------------------------------------------------------
echo -e "${BOLD}${BLUE}▼ CONFIGURATION${NC}"
echo ""
printf "  %-30s %s\n" "install/utils/select_clients.sh" "Client recommendations by hardware"
printf "  %-30s %s\n" "install/utils/run_manifest.sh" "Phase-aware runner (--phase1, --phase2)"
echo ""

# -----------------------------------------------------------------------------
# OPTIONAL & ADVANCED
# -----------------------------------------------------------------------------
echo -e "${BOLD}${BLUE}▼ OPTIONAL & ADVANCED${NC}"
echo ""
printf "  %-30s %s\n" "install/utils/optional_tools.sh" "Network monitoring (bmon, slurm, tcptrack)"
printf "  %-30s %s\n" "install/utils/purge_ethereum_data.sh" "Remove client data for clean switch (--confirm)"
printf "  %-30s %s\n" "install/ssl/install_acme_ssl.sh" "SSL via acme.sh (recommended)"
printf "  %-30s %s\n" "install/ssl/install_ssl_certbot.sh" "SSL via Certbot"
printf "  %-30s %s\n" "install/web/install_nginx.sh" "Nginx (HTTP only)"
printf "  %-30s %s\n" "install/web/install_caddy.sh" "Caddy web server"
echo ""

# -----------------------------------------------------------------------------
# SECURITY
# -----------------------------------------------------------------------------
echo -e "${BOLD}${BLUE}▼ SECURITY VERIFICATION${NC}"
echo ""
printf "  %-30s %s\n" "docs/verify_security.sh" "Verify security configuration"
printf "  %-30s %s\n" "docs/server_security_validation.sh" "Comprehensive security validation"
echo ""

# -----------------------------------------------------------------------------
# QUICK REFERENCE
# -----------------------------------------------------------------------------
echo -e "${BOLD}${GREEN}▼ QUICK REFERENCE${NC}"
echo ""
echo "  Service control:  sudo systemctl [start|stop|restart|status] eth1 cl validator mev"
echo "  Config file:      exports.sh (and config/user_config.env after configure)"
echo "  Docs:             docs/README.md, docs/SCRIPTS.md, docs/WORKFLOW.md"
echo ""
echo -e "  Run ${BOLD}./help.sh${NC} anytime to see this reference."
echo ""
