import type { MetadataRoute } from 'next'
import { ARTICLES } from '@/lib/articles'
import { SITE_CONFIG } from '@/lib/constants'

// Static routes worth indexing. Blog articles get a higher priority since
// they're the pages we want people to find and share.
const staticRoutes: { path: string; priority: number }[] = [
  { path: '', priority: 1 },
  { path: '/quickstart', priority: 0.7 },
  { path: '/agents', priority: 0.6 },
  { path: '/blog', priority: 0.7 },
  // Served from frontend/public/ (generated by scripts/sync-llms.mjs from the
  // repo-root llms.txt / llms-full.txt) — see docs/GEO_AEO_DISCOVERABILITY_PLAN.md A2.
  { path: '/llms.txt', priority: 0.3 },
  { path: '/llms-full.txt', priority: 0.2 },
]

const blogRoutes: { path: string; priority: number }[] = ARTICLES.map((article) => ({
  path: `/blog/${article.slug}`,
  priority: article.sitemapPriority,
}))

const routes: { path: string; priority: number }[] = [
  ...staticRoutes,
  ...blogRoutes,
  { path: '/deck/bakeoff.html', priority: 0.6 },
]

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map(({ path, priority }) => ({
    url: `${SITE_CONFIG.url}${path}`,
    changeFrequency: 'monthly',
    priority,
  }))
}
