'use client';

import { useState, useEffect } from 'react';
import clientsData from '@/data/clients.json';
import Link from 'next/link';

type Client = {
  id: string;
  type: 'execution' | 'consensus';
  name: string;
  language: string;
  tagline: string;
  features: string[];
  drawbacks: string[];
  install_script: string;
};

type Config = {
  network: 'mainnet' | 'holesky';
  hardware: 'high' | 'mid' | 'low';
  executionClient: string;
  consensusClient: string;
  mev: 'mev-boost' | 'commit-boost' | 'none';
  feeRecipient: string;
  graffiti: string;
};

const initialConfig: Config = {
  network: 'mainnet',
  hardware: 'mid',
  executionClient: '',
  consensusClient: '',
  mev: 'mev-boost',
  feeRecipient: '',
  graffiti: 'Eth2QuickStart',
};

export default function Wizard() {
  const [step, setStep] = useState(1);
  const [config, setConfig] = useState<Config>(initialConfig);
  const [generatedScript, setGeneratedScript] = useState('');

  // Auto-select clients based on hardware when hardware changes
  useEffect(() => {
    if (config.executionClient === '' || config.consensusClient === '') {
      recommendClients(config.hardware);
    }
  }, [config.hardware]);

  const recommendClients = (hw: string) => {
    let exec = 'geth';
    let cons = 'prysm';

    if (hw === 'high') {
      exec = 'reth';
      cons = 'lighthouse';
    } else if (hw === 'low') {
      exec = 'nimbus_eth1';
      cons = 'nimbus';
    }
    
    setConfig(prev => ({
      ...prev,
      executionClient: exec,
      consensusClient: cons
    }));
  };

  const generateManifest = () => {
    const envContent = `
export ETH_NETWORK='${config.network}'
export FEE_RECIPIENT='${config.feeRecipient}'
export GRAFITTI='${config.graffiti}'
# Execution Client: ${config.executionClient}
# Consensus Client: ${config.consensusClient}
    `.trim();

    const manifestContent = `
#!/bin/bash
# Manifest generated by Web Wizard
set -e

echo 'Starting Installation based on Manifest...'
./run_1.sh
./install/execution/${config.executionClient}.sh
./install/consensus/${config.consensusClient}.sh
${config.mev === 'mev-boost' ? './install/mev/install_mev_boost.sh' : ''}
${config.mev === 'commit-boost' ? './install/mev/install_commit_boost.sh' : ''}
    `.trim();

    setGeneratedScript(manifestContent);
    setStep(6); // Go to result step
  };

  const nextStep = () => setStep(s => s + 1);
  const prevStep = () => setStep(s => s - 1);

  return (
    <div className="w-full max-w-4xl mx-auto">
      {/* Progress Bar */}
      <div className="mb-8 flex justify-between text-sm uppercase tracking-wider opacity-60">
        <span className={step >= 1 ? 'text-green-400' : ''}>1. Network</span>
        <span className={step >= 2 ? 'text-green-400' : ''}>2. Hardware</span>
        <span className={step >= 3 ? 'text-green-400' : ''}>3. Clients</span>
        <span className={step >= 4 ? 'text-green-400' : ''}>4. MEV</span>
        <span className={step >= 5 ? 'text-green-400' : ''}>5. Review</span>
      </div>

      <div className="bg-gray-900 border border-green-800 p-8 rounded-xl shadow-2xl min-h-[400px]">
        {/* Step 1: Network */}
        {step === 1 && (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-white">Select Network</h2>
            <div className="grid md:grid-cols-2 gap-4">
              <button
                onClick={() => setConfig({ ...config, network: 'mainnet' })}
                className={`p-6 border rounded-lg text-left transition-all ${
                  config.network === 'mainnet' ? 'border-green-500 bg-green-900/20' : 'border-gray-700 hover:border-green-500/50'
                }`}
              >
                <div className="font-bold text-lg mb-2">Mainnet</div>
                <div className="text-sm opacity-70">Real value, production network.</div>
              </button>
              <button
                onClick={() => setConfig({ ...config, network: 'holesky' })}
                className={`p-6 border rounded-lg text-left transition-all ${
                  config.network === 'holesky' ? 'border-green-500 bg-green-900/20' : 'border-gray-700 hover:border-green-500/50'
                }`}
              >
                <div className="font-bold text-lg mb-2">Holesky</div>
                <div className="text-sm opacity-70">Testnet, no real value. Good for practice.</div>
              </button>
            </div>
          </div>
        )}

        {/* Step 2: Hardware */}
        {step === 2 && (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-white">Hardware Profile</h2>
            <div className="grid gap-4">
              {[
                { id: 'high', label: 'High-End', desc: '32GB+ RAM, 2TB+ NVMe - Best Performance' },
                { id: 'mid', label: 'Mid-Range', desc: '16GB RAM, SSD - Balanced' },
                { id: 'low', label: 'Low-Resource', desc: '8GB RAM - Efficiency First' }
              ].map((hw) => (
                <button
                  key={hw.id}
                  onClick={() => {
                    setConfig({ ...config, hardware: hw.id as any });
                    recommendClients(hw.id);
                  }}
                  className={`p-6 border rounded-lg text-left transition-all ${
                    config.hardware === hw.id ? 'border-green-500 bg-green-900/20' : 'border-gray-700 hover:border-green-500/50'
                  }`}
                >
                  <div className="font-bold text-lg mb-1">{hw.label}</div>
                  <div className="text-sm opacity-70">{hw.desc}</div>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Step 3: Clients */}
        {step === 3 && (
          <div className="space-y-8">
            <h2 className="text-2xl font-bold text-white">Select Clients</h2>
            
            {/* Execution Clients */}
            <div>
              <h3 className="text-lg font-bold text-green-400 mb-4 border-b border-green-900 pb-2">Execution Client</h3>
              <div className="grid md:grid-cols-2 gap-4">
                {clientsData.filter(c => c.type === 'execution').map((client) => (
                  <button
                    key={client.id}
                    onClick={() => setConfig({ ...config, executionClient: client.id })}
                    className={`p-4 border rounded-lg text-left transition-all h-full ${
                      config.executionClient === client.id ? 'border-green-500 bg-green-900/20' : 'border-gray-700 hover:border-green-500/50'
                    }`}
                  >
                    <div className="flex justify-between items-center mb-2">
                      <span className="font-bold">{client.name}</span>
                      <span className="text-xs bg-gray-800 px-2 py-1 rounded">{client.language}</span>
                    </div>
                    <p className="text-xs opacity-70 mb-2">{client.tagline}</p>
                  </button>
                ))}
              </div>
            </div>

            {/* Consensus Clients */}
            <div>
              <h3 className="text-lg font-bold text-green-400 mb-4 border-b border-green-900 pb-2">Consensus Client</h3>
              <div className="grid md:grid-cols-2 gap-4">
                {clientsData.filter(c => c.type === 'consensus').map((client) => (
                  <button
                    key={client.id}
                    onClick={() => setConfig({ ...config, consensusClient: client.id })}
                    className={`p-4 border rounded-lg text-left transition-all h-full ${
                      config.consensusClient === client.id ? 'border-green-500 bg-green-900/20' : 'border-gray-700 hover:border-green-500/50'
                    }`}
                  >
                    <div className="flex justify-between items-center mb-2">
                      <span className="font-bold">{client.name}</span>
                      <span className="text-xs bg-gray-800 px-2 py-1 rounded">{client.language}</span>
                    </div>
                    <p className="text-xs opacity-70 mb-2">{client.tagline}</p>
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Step 4: MEV & Extras */}
        {step === 4 && (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-white">MEV & Rewards</h2>
            
            {/* MEV Selection */}
            <div>
              <label className="block text-sm font-bold mb-3 uppercase tracking-wider text-green-400">MEV Solution</label>
              <div className="grid gap-4">
                {[
                  { id: 'mev-boost', label: 'MEV-Boost (Standard)', desc: 'The industry standard. Highly recommended.' },
                  { id: 'commit-boost', label: 'Commit-Boost (Advanced)', desc: 'Modular, newer architecture.' },
                  { id: 'none', label: 'None', desc: 'No extra rewards. Not recommended.' }
                ].map((opt) => (
                  <button
                    key={opt.id}
                    onClick={() => setConfig({ ...config, mev: opt.id as any })}
                    className={`p-4 border rounded-lg text-left transition-all ${
                      config.mev === opt.id ? 'border-green-500 bg-green-900/20' : 'border-gray-700 hover:border-green-500/50'
                    }`}
                  >
                    <div className="font-bold">{opt.label}</div>
                    <div className="text-sm opacity-60">{opt.desc}</div>
                  </button>
                ))}
              </div>
            </div>

            {/* Inputs */}
            <div className="grid gap-6 mt-6">
              <div>
                <label className="block text-sm font-bold mb-2 uppercase tracking-wider text-green-400">Fee Recipient Address</label>
                <input 
                  type="text" 
                  value={config.feeRecipient}
                  onChange={(e) => setConfig({...config, feeRecipient: e.target.value})}
                  placeholder="0x..."
                  className="w-full bg-black border border-gray-700 rounded p-3 text-white focus:border-green-500 outline-none font-mono"
                />
                <p className="text-xs text-gray-500 mt-1">Your ETH address to receive rewards.</p>
              </div>
              <div>
                <label className="block text-sm font-bold mb-2 uppercase tracking-wider text-green-400">Graffiti</label>
                <input 
                  type="text" 
                  value={config.graffiti}
                  onChange={(e) => setConfig({...config, graffiti: e.target.value})}
                  maxLength={32}
                  className="w-full bg-black border border-gray-700 rounded p-3 text-white focus:border-green-500 outline-none font-mono"
                />
                <p className="text-xs text-gray-500 mt-1">Public text included in your proposed blocks (max 32 chars).</p>
              </div>
            </div>
          </div>
        )}

        {/* Step 5: Review */}
        {step === 5 && (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-white">Review Configuration</h2>
            
            <div className="bg-black p-6 rounded border border-gray-800 font-mono text-sm space-y-4">
              <div className="grid grid-cols-2">
                <span className="opacity-50">Network:</span>
                <span className="text-right text-green-400">{config.network}</span>
              </div>
              <div className="grid grid-cols-2">
                <span className="opacity-50">Hardware:</span>
                <span className="text-right text-green-400">{config.hardware}</span>
              </div>
              <div className="border-t border-gray-800 my-2"></div>
              <div className="grid grid-cols-2">
                <span className="opacity-50">Execution Client:</span>
                <span className="text-right text-yellow-400">{config.executionClient}</span>
              </div>
              <div className="grid grid-cols-2">
                <span className="opacity-50">Consensus Client:</span>
                <span className="text-right text-blue-400">{config.consensusClient}</span>
              </div>
              <div className="border-t border-gray-800 my-2"></div>
              <div className="grid grid-cols-2">
                <span className="opacity-50">MEV:</span>
                <span className="text-right text-purple-400">{config.mev}</span>
              </div>
              <div className="grid grid-cols-2">
                <span className="opacity-50">Fee Recipient:</span>
                <span className="text-right break-all">{config.feeRecipient || '(Not Set)'}</span>
              </div>
            </div>
          </div>
        )}

        {/* Step 6: Result */}
        {step === 6 && (
          <div className="space-y-6 text-center">
            <h2 className="text-3xl font-bold text-green-500">Manifest Generated!</h2>
            <p className="opacity-70">Run this command on your server to start the installation:</p>
            
            <div className="bg-black p-6 rounded border border-green-500 font-mono text-left overflow-x-auto relative group">
              <pre className="text-green-300 whitespace-pre-wrap break-all">
                {`curl -fsSL https://eth2-quickstart.vercel.app/install.sh | \\
ETH_NETWORK=${config.network} \\
EXECUTION_CLIENT=${config.executionClient} \\
CONSENSUS_CLIENT=${config.consensusClient} \\
MEV_SOLUTION=${config.mev} \\
bash`}
              </pre>
            </div>

            <div className="mt-8 pt-8 border-t border-gray-800">
               <h3 className="text-xl font-bold mb-4">Or Download Manifest</h3>
               <textarea 
                  readOnly 
                  value={generatedScript}
                  className="w-full h-48 bg-gray-950 border border-gray-800 rounded p-4 font-mono text-xs text-gray-400 focus:outline-none"
               />
            </div>
            
            <div className="mt-8">
              <Link href="/" className="text-green-500 hover:underline">&larr; Back to Home</Link>
            </div>
          </div>
        )}
      </div>

      {/* Navigation Buttons */}
      {step < 6 && (
        <div className="mt-8 flex justify-between">
          <button
            onClick={prevStep}
            disabled={step === 1}
            className={`px-6 py-3 rounded font-bold transition-all ${
              step === 1 ? 'opacity-0 pointer-events-none' : 'text-gray-400 hover:text-white border border-gray-700 hover:border-gray-500'
            }`}
          >
            &larr; Back
          </button>
          
          {step === 5 ? (
             <button
              onClick={generateManifest}
              className="px-8 py-3 bg-green-600 hover:bg-green-500 text-black font-bold rounded shadow-[0_0_20px_rgba(34,197,94,0.3)] hover:shadow-[0_0_30px_rgba(34,197,94,0.5)] transition-all"
            >
              Generate Manifest &rarr;
            </button>
          ) : (
            <button
              onClick={nextStep}
              className="px-8 py-3 bg-white text-black font-bold rounded hover:bg-gray-200 transition-all"
            >
              Next Step &rarr;
            </button>
          )}
        </div>
      )}
    </div>
  );
}
