#!/bin/bash

# Configuration Wizard for Eth2 Quick Start
# Uses whiptail to prompt the user and generates config/user_config.env

set -e

# Colors
GREEN='\033[0;32m'
NC='\033[0m'

# Ensure config directory exists
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../" && pwd)"
CONFIG_DIR="$ROOT_DIR/config"
CONFIG_FILE="$CONFIG_DIR/user_config.env"
INSTALL_MANIFEST="$ROOT_DIR/install_manifest.sh"

mkdir -p "$CONFIG_DIR"

# Helper for whiptail
function show_msg() {
    whiptail --title "Eth2 Quick Start" --msgbox "$1" 10 60
}

# Check if whiptail is installed
if ! command -v whiptail &> /dev/null; then
    echo "Whiptail not found. Installing..."
    sudo apt-get update && sudo apt-get install -y whiptail
fi

# Welcome
whiptail --title "Eth2 Quick Start Wizard" --msgbox "Welcome to the Ethereum Node Setup Wizard.\n\nThis tool will guide you through configuring your node.\n\nIt will generate a configuration file at $CONFIG_FILE." 12 70

# 1. Network Selection
NETWORK=$(whiptail --title "Network Selection" --menu "Choose the Ethereum Network:" 15 60 2 \
"mainnet" "Ethereum Mainnet (Real Value)" \
"holesky" "Holesky Testnet (Testing)" 3>&1 1>&2 2>&3)
if [ $? -ne 0 ]; then exit 0; fi

# 2. Client Selection Strategy
HARDWARE=$(whiptail --title "Hardware Profile" --menu "Select your hardware profile:" 15 60 3 \
"high" "High-End (32GB+ RAM, 2TB+ NVMe) - Best Performance" \
"mid" "Mid-Range (16GB RAM, SSD) - Balanced" \
"low" "Low-Resource (8GB RAM) - Efficiency First" 3>&1 1>&2 2>&3)

# Recommend clients based on hardware
case $HARDWARE in
    "high")
        REC_EXEC="reth"
        REC_CONS="lighthouse"
        ;;
    "mid")
        REC_EXEC="geth"
        REC_CONS="prysm"
        ;;
    "low")
        REC_EXEC="nimbus_eth1"
        REC_CONS="nimbus"
        ;;
esac

# Confirm Client Selection
whiptail --title "Client Recommendations" --yesno "Based on your hardware, we recommend:\n\nExecution: $REC_EXEC\nConsensus: $REC_CONS\n\nDo you want to use these defaults?" 12 60
USE_DEFAULTS=$?

if [ $USE_DEFAULTS -eq 0 ]; then
    EXEC_CLIENT=$REC_EXEC
    CONS_CLIENT=$REC_CONS
else
    # Manual Selection
    EXEC_CLIENT=$(whiptail --title "Execution Client" --menu "Select Execution Client:" 15 60 5 \
    "geth" "Geth (Go) - Stable, Popular" \
    "nethermind" "Nethermind (C#) - Enterprise" \
    "besu" "Besu (Java) - Enterprise" \
    "erigon" "Erigon (Go) - Archival/Fast" \
    "reth" "Reth (Rust) - High Performance" \
    "nimbus_eth1" "Nimbus (Nim) - Lightweight" 3>&1 1>&2 2>&3)
    
    CONS_CLIENT=$(whiptail --title "Consensus Client" --menu "Select Consensus Client:" 15 60 5 \
    "prysm" "Prysm (Go) - Popular, Easy" \
    "lighthouse" "Lighthouse (Rust) - Secure, Fast" \
    "teku" "Teku (Java) - Institutional" \
    "nimbus" "Nimbus (Nim) - Lightweight" \
    "lodestar" "Lodestar (TS) - JS/TS Ecosystem" \
    "grandine" "Grandine (Rust) - Fast (Beta)" 3>&1 1>&2 2>&3)
fi

# 3. MEV Selection
MEV_CHOICE=$(whiptail --title "MEV Configuration" --menu "Select MEV Solution (for validator rewards):" 15 70 3 \
"mev-boost" "MEV-Boost (Standard) - Recommended" \
"commit-boost" "Commit-Boost (Advanced) - Modular" \
"none" "None - No extra rewards (Not Recommended)" 3>&1 1>&2 2>&3)

# 4. Fee Recipient
FEE_RECIPIENT=$(whiptail --title "Fee Recipient" --inputbox "Enter your ETH address for rewards:" 10 60 "0x0000000000000000000000000000000000000000" 3>&1 1>&2 2>&3)

# 5. Graffiti
GRAFFITI=$(whiptail --title "Graffiti" --inputbox "Enter your validator graffiti (public note on blocks):" 10 60 "Eth2QuickStart" 3>&1 1>&2 2>&3)

# 6. Generate Configuration
echo "# Auto-generated by configure.sh on $(date)" > "$CONFIG_FILE"
echo "export ETH_NETWORK='$NETWORK'" >> "$CONFIG_FILE"
echo "export FEE_RECIPIENT='$FEE_RECIPIENT'" >> "$CONFIG_FILE"
echo "export GRAFITTI='$GRAFFITI'" >> "$CONFIG_FILE"

# Map client names to script paths or variables expected by other scripts
# Currently existing scripts often hardcode clients or rely on the user running the specific script.
# We will create an 'install_manifest.sh' that the master installer can run.

echo "# Execution Client: $EXEC_CLIENT" >> "$CONFIG_FILE"
echo "# Consensus Client: $CONS_CLIENT" >> "$CONFIG_FILE"

# Generate Manifest
echo "#!/bin/bash" > "$INSTALL_MANIFEST"
echo "# Manifest generated on $(date)" >> "$INSTALL_MANIFEST"
echo "set -e" >> "$INSTALL_MANIFEST"
echo "" >> "$INSTALL_MANIFEST"
echo "echo 'Starting Installation based on Manifest...'" >> "$INSTALL_MANIFEST"

# Add System Setup
echo "./run_1.sh" >> "$INSTALL_MANIFEST"

# Add Client Installs
# We assume the scripts are in install/execution/CLIENT.sh and install/consensus/CLIENT.sh
echo "./install/execution/$EXEC_CLIENT.sh" >> "$INSTALL_MANIFEST"
echo "./install/consensus/$CONS_CLIENT.sh" >> "$INSTALL_MANIFEST"

# Add MEV Install
if [ "$MEV_CHOICE" == "mev-boost" ]; then
    echo "./install/mev/install_mev_boost.sh" >> "$INSTALL_MANIFEST"
elif [ "$MEV_CHOICE" == "commit-boost" ]; then
    echo "./install/mev/install_commit_boost.sh" >> "$INSTALL_MANIFEST"
fi

chmod +x "$INSTALL_MANIFEST"

show_msg "Configuration Complete!\n\n1. Config saved to: $CONFIG_FILE\n2. Manifest saved to: $INSTALL_MANIFEST\n\nRun './install_manifest.sh' (or reboot and run it) to apply changes."

# Offer to run it now?
if (whiptail --title "Run Installation?" --yesno "Do you want to run the installation now? (Requires sudo)" 10 60); then
    clear
    echo "Running installation..."
    sudo "$INSTALL_MANIFEST"
else
    clear
    echo "Setup complete. Run ./install_manifest.sh when ready."
fi
